### ISSUE TITLE
姓名识别错误

### ISSUE THREAD

**Issue by EbolaEmperor** [fjzzq2002/fjzzq2002.github.io#10]
您好，您数据库里的赣州中学“黄文翀”与“黄文”，实际上是同一个人（黄文翀），您最近更新数据的时候可能没识别出这个“翀”字。

**Comment by fjzzq2002** [comment]
理论上我更新过了啊... #8

**Comment by fjzzq2002** [comment]
你可能需要ctrl+f5刷新一下之类的

**Comment by EbolaEmperor** [comment]
不是的，不是更新问题。获奖情况的确更新了，但姓名识别错了。不信您搜一下“赣州中学”，您就会发现有“黄文翀”和“黄文”两个人。但其实根本没有“黄文”这个人，那个名字下的获奖信息，应该是“黄文翀”的

**Comment by fjzzq2002** [comment]
十分抱歉，数据源那边改了，但是之前忘了运行那个更新数据的脚本。

**Comment by PhoenixStarEclipse** [comment]
您好，您数据库里的苏州中学“许澔天”与“许天”为同一个人，您最近更新数据的时候可能没识别出这个“澔”字。
