### ISSUE TITLE
同名合并有问题

### ISSUE THREAD

**Issue by Prurite** [fjzzq2002/fjzzq2002.github.io#15]
如题，比如 https://www.k-xzy.xyz/oier_db/?f=pv%3D%3D%22%u56DB%u5DDD%22%26%26nm%3D%3D%22%u674E%u601D%u6770%22 这个查询中，本来位于两个截然不同的地点的同名选手被错误地合并到了一起（话说一年参加两次普及本身就很有问题吧）

**Comment by fjzzq2002** [comment]
对于这个问题目前没有找到什么好的解决方法。如果你有除了人工修改数据以外的方法欢迎提出。
