### ISSUE TITLE
[oier-db] todo

### ISSUE THREAD

**Issue by fjzzq2002** [fjzzq2002/fjzzq2002.github.io#2]
1. [x] 把同一个人合并
主要的技术障碍是可能有人同省而且重名
2. [x] rating
按每个人的获奖情况大致评出每个人的水平，并支持按水平排序
3. [x] compress
把代码压缩一下
4. [x] 写个脚本自动从noi官网上抓取数据
半自动抓取还是太累了= =
5. [ ] 关联codeforces等账号

也欢迎大家提出新的建议

**Comment by test12345-pupil** [comment]
为什么要把同一个人合并到他的初中。。。

**Comment by fjzzq2002** [comment]
啥意思啊...求sample

**Comment by test12345-pupil** [comment]
http://orzyanqval.site/oier_db/?f=nm%3D%3D%22%u738B%u7FBF%u6DB5%22
湖南OIer王羿涵，男，现在高三，曾在长沙市长郡中学学习，现在在长沙市长郡双语实验学校学习。
= =

**Comment by fjzzq2002** [comment]
可能修复了吧= = 下次最好提新的issue，这样不大方便

**Comment by fjzzq2002** [comment]
暂时关掉了合并学校的功能，因为发现一些学校被误合并了，等到有更科学的合并方法后会修复

**Comment by TechCiel** [comment]
私以为，加rating不如加分数

**Comment by fjzzq2002** [comment]
~~是的，这个打算改回去，但是最近没啥时间写~~
改成分数了

**Comment by TechCiel** [comment]
顺便，直接把整个数据库扔到前端太暴力啦

**Comment by fjzzq2002** [comment]
穷

**Comment by zhuoyuc** [comment]
要不要尝试用一下coding.net 的动态pages
毕竟支持mysql+php
https://coding.net/help/doc/pages/dpages.html

**Comment by fjzzq2002** [comment]
我觉得那个听起来就续不了多久（
现在数据库会在localstorage里缓存了，访问速度应该会比较快了

**Comment by zhuoyuc** [comment]
还行吧……rxz的博客就是用那个搭的

**Comment by zhuoyuc** [comment]
要不要加上常用id？不过工程量很大的样子……

**Comment by TechCiel** [comment]
常用ID不存在的，会需要大量人力维护

**Comment by fjzzq2002** [comment]
由于域名快到期了，所以搬到了http://oierdb.com

**Comment by hfctf0210** [comment]
安徽OIer陈宇，男，现在初三，曾在安徽省无为中学学习，现在在芜湖市第二十七中学学习。评分 29.66（Rank 1921）
曾获得NOIP2015普及组二等奖、NOIP2016提高组二等奖、NOIP2016普及组一等奖、NOIP2017提高组一等奖、NOIP2017普及组一等奖、WC2018铜牌
注：无为中学的陈宇获得NOIP2016提高组二等奖，现在高三；其余的奖项均为芜湖27中的陈宇

**Comment by hfctf0210** [comment]
http://oierdb.com/oier_db/?f=nm%3D%3D%22%u9648%u5B87%22

**Comment by fjzzq2002** [comment]
常规操作，原因如下：
本数据库从noi官网获取信息，能得到的只有选手的姓名、省份、学校、年龄等，目前数据库区分人仅仅用的是`姓名+省份`，如果要区分同省同名者需要用`姓名+年龄`，但是这样就可能出现跳级/复读/登记错年级者被分为多个（`姓名+学校`就算了，初中升高中总要允许）。
有空加一个切换按钮啥的吧...

**Comment by hfctf0210** [comment]
请问评分生成公式是什么？

**Comment by fjzzq2002** [comment]
不是很好描述，大致是每个奖按排名和奖牌评分，同类奖的评分排序后按1 1/2 1/4为系数这样加在一起。具体的自己看代码吧......
https://github.com/fjzzq2002/fjzzq2002.github.io/blob/master/oier_db/calcrating.py

**Comment by memset0** [comment]
@fjzzq2002 动态 Pages 倒掉啦，您大佬的预判好正确啊！

@KingSann 阮行止大佬的博客貌似是用静态 Pages 搭的。。。

**Comment by zhuoyuc** [comment]
@memset0 于是我现在转github pages啦（逃

**Comment by memset0** [comment]
@KingSann 感觉 Coding 这样发展下去对不付费的用户可能越来越不友好

但至少 Coding 决定走和 Github 不一样的路应该还算正确的，毕竟 Github 在国内也发展的很好，只能兹滋一下然后也逃了。。。。

**Comment by zhuoyuc** [comment]
@memset0 毕竟又不赚钱而且似乎又涉及到了备案……主要原因还是推广cloudstudio来服（zhuan）务（qian）大众吧……

**Comment by hfctf0210** [comment]
貌似网站死了

**Comment by fjzzq2002** [comment]
看不出来（

**Comment by ghost** [comment]
@KingSann CloudStudio又将发展成付费版云IDE+Pages，就这么个发财策略

**Comment by memset0** [comment]
@hiuseues 你总得让人Coding赚点钱嘛，毕竟能活到现在已经很不错了

**Comment by KingSann** [comment]
@hiuseues 不过[webide](ide.coding.net)还或者已经不错了……至少还能让我部署一下hexo……

**Comment by KingSann** [comment]
@hiuseues 不过webide还或者已经不错了……至少还能让我部署一下hexo……

**Comment by zhuoyuc** [comment]
@hiuseues 不过webide还活着已经不错了……至少还能让我部署一下hexo……

**Comment by wseqwq** [comment]
话说为啥要用评分啊……Rating挺好的呀

**Comment by hfctf0210** [comment]
怎么现在oierdb.com上不去了？

**Comment by fjzzq2002** [comment]
看不出来

**Comment by hfctf0210** [comment]
江西OIer黄文，男，现在高一，在赣州中学学习。评分 11.36（Rank 2817）
曾获得NOI2018铜牌。
打漏了一个字

**Comment by hfctf0210** [comment]
还有感觉NOIP的占比提高了，NOI/CTSC/APIO的占比减少了

**Comment by fjzzq2002** [comment]
评分方式改变了。。这个ysy背锅。。

**Comment by fjzzq2002** [comment]
数据问题两天前就修复了...你看看版本号是不是v0.13.2

**Comment by ghost** [comment]
有个好看点的前端能Pull Request吗……一直有人在吐槽这界面

**Comment by fjzzq2002** [comment]
输入框改了...现在大概输入方便点了
下面的部分我个人觉得海星（
如果你有更好看的前端求pr

**Comment by humuyan** [comment]
建议增加历史排名

**Comment by fjzzq2002** [comment]
实现起来有点痛苦啊。。有空就实现吧
