### ISSUE TITLE
额...这里有两个我...

### ISSUE THREAD

**Issue by rqy2002** [fjzzq2002/fjzzq2002.github.io#3]
http://orzyanqval.site/oier_db/?id=%E6%B5%8E%E5%8D%97%E5%B8%82%E7%A8%BC%E8%BD%A9%E5%AD%A6%E6%A0%A1%20%E4%BB%BB%E6%B8%85%E5%AE%87
http://orzyanqval.site/oier_db/?id=%E5%B1%B1%E4%B8%9C%E7%9C%81%E6%B5%8E%E5%8D%97%E7%A8%BC%E8%BD%A9%E5%AD%A6%E6%A0%A1%20%E4%BB%BB%E6%B8%85%E5%AE%87
一段时间之前还没有

**Comment by rqy2002** [comment]
嗯，在2017-11-26还没有

**Comment by rqy1458814497** [comment]
诶不对啊

**Comment by fjzzq2002** [comment]
哦，刚刚发的bugfix好像出锅了，我再改改

**Comment by fjzzq2002** [comment]
fixed
